doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        types:
            awardedAt:    App\Infrastructure\Doctrine\Type\AwardedAtType
            redeemedAt:   App\Infrastructure\Doctrine\Type\RedeemedAtType
            clientName:   App\Infrastructure\Doctrine\Type\ClientNameType
            pharmacyName: App\Infrastructure\Doctrine\Type\PharmacyNameType
        mapping_types:
            awardedAt:    datetime
            redeemedAt:   datetime
            clientName:   string
            pharmacyName: string
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/orm'
                prefix: 'App\Domain\Entity'
                alias: Domain
