doctrine:
    dbal:
        default_connection: default
        types:
            awardedAt:    App\Infrastructure\Doctrine\Type\AwardedAtType
            redeemedAt:   App\Infrastructure\Doctrine\Type\RedeemedAtType
            clientName:   App\Infrastructure\Doctrine\Type\ClientNameType
            pharmacyName: App\Infrastructure\Doctrine\Type\PharmacyNameType
        connections:
            default:
                url: '%env(resolve:DB_READ)%'
                server_version: '5.7'
                driver: 'pdo_mysql'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                mapping_types:
                    awardedAt:    datetime
                    redeemedAt:   datetime
                    clientName:   string
                    pharmacyName: string
            writer:
                url: '%env(resolve:DB_WRITE)%'
                server_version: '5.7'
                driver: 'pdo_mysql'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                mapping_types:
                    awardedAt:    datetime
                    redeemedAt:   datetime
                    clientName:   string
                    pharmacyName: string

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    Domain:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/config/mapping/orm'
                        prefix: 'App\Domain\Entity'
                        alias: Domain
            writer:
                connection: writer
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                mappings:
                    Domain:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/config/mapping/orm'
                        prefix: 'App\Domain\Entity'
                        alias: Domain

#when@test:
#    doctrine:
#        dbal:
#            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system