version:  '3'

services:
  mysql:
    container_name: mysql-pharma
    image: mysql:8.0
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306

  web:
    restart: on-failure
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
        USER: ${USER}
        USER_NAME: ${USER_NAME}
        USER_EMAIL: ${USER_EMAIL}
        USER_ID: ${USER_ID}
    volumes:
      - ./:/var/www/app
      - ./var/log:/var/www/app/var/log

  nginx:
    container_name: ${APP}
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - ./public/:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/log:/var/log/nginx
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - web

  adminer:
    container_name: adminer-pharma
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080
