subscribers:
    LogSubscriber:
        events:
            - '*'
    PersistSubscriber:
        events:
            - ClientWasCreated
            - PharmacyWasCreated
            - PointWasCreated
            - PointWasRedeemed