web_controllers:
  resource: ../src/UI/Http/Web/Controller/
  type: annotation
  prefix: /

api_controllers:
  resource: ../src/UI/Http/ApiRest/Controller/
  type: annotation
  prefix: /api

kernel:
  resource: ../src/Infrastructure/Symfony/Kernel.php
  type: annotation

#index:
#    path: /
#    controller: App\Controller\DefaultController::index

